### ISSUE TITLE
سلام

### ISSUE THREAD

**Issue by mohsen202** [othneildrew/Best-README-Template#118]
سلام و سپاس از زحمات شما
من این ارور رو دارم  . ممنون مشم راهنمایی بفرمایید
    with io.open(outputfile, 'w', encoding='utf8') as f:
IsADirectoryError: [Errno 21] Is a directory: 'outputfile'

سپاس 
### Steps to reproduce
Steps to reproduce the behavior.

### Environment
 - OS: [e.g. Arch Linux]
 - Other details that you think may affect.

**Comment by piwonka** [comment]
This looks like a python error message and does not seem to have anything to do with this project. I think this issue can be closed, since this is propably not the right place to ask this question. :)

A bit of Advice though @mohsen202:
It seems you are trying to write to a file, but the path you specify for the io.open call seems to be a directory.
